services:
  - type: web
    name: image-compressor-backend
    env: node
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
    plan: free
